#version: '3'
#
#services:
####> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-15}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
####< doctrine/doctrine-bundle ###
#
#volumes:
####> doctrine/doctrine-bundle ###
#  database_data:
####< doctrine/doctrine-bundle ###
version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: movies
    image: mariadb:${MARIADB_VERSION:-10.6}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-movies}
      MYSQL_ROOT_PASSWORD: user
      MYSQL_USER: ${DATABASE_USER:-user}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-user}
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
